### ISSUE TITLE
honor `/etc/config/dhcp` and `/etc/config/network`

### ISSUE THREAD

**Issue by aparcar** [sargon/ddhcpd#17]
New users (including me) are likely confused by using the [raw DHCP codes](https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol#Documented_in_RFC_2132) so the service file could be extended honoring `dhcp` and `network` settings.

Or any reasons against that?

**Comment by sargon** [comment]
I actually startet to read information out of the environment during startup, but thats more a topic of gluon-sargon package description, have a look into the v2018.x branch.

Furthermore that are openwrt depending files, so no ddhcpd will never honor them directly.
