### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by aparcar** [sargon/ddhcpd#18]
LibreMesh uses `dnsmasq-dhcpv6` and lease sharing via `alfred` to allow IPv6 roaming. Would it be possible to integrate IPV6 support here as well so it'd be a full DHCP replacement?

**Comment by sargon** [comment]
DHCPv6 is a completely different approach to DHCP. And to my knowledge only used for service announcements (e.g. NTP, DNS, WINS) so the network configuration is still handled via router advertisements.

**Comment by aparcar** [comment]
Thanks for that clarification
